// Generated by CoffeeScript 1.6.3
(function() {
  var Q, r, request, _create_method;

  Q = require('q');

  r = require('request');

  request = function(uri, options) {
    var deferred, req;
    if (options == null) {
      options = {};
    }
    deferred = Q.defer();
    req = r(uri, options, function(err, res) {
      if (err) {
        return deferred.reject(err);
      } else {
        return deferred.resolve(res);
      }
    });
    return deferred.promise;
  };

  _create_method = function(uri, options, method) {
    var params, _ref, _request;
    if (options == null) {
      options = {};
    }
    params = r.initParams(uri, options, null);
    params.options.method = method;
    if (typeof ((_ref = params.options) != null ? _ref._requester : void 0) === 'function') {
      _request = params.options._requester;
    } else {
      _request = request;
    }
    return _request(params.uri || null, params.options);
  };

  request.get = function(uri, options) {
    return _create_method(uri, options, 'GET');
  };

  request.post = function(uri, options) {
    return _create_method(uri, options, 'POST');
  };

  request.put = function(uri, options) {
    return _create_method(uri, options, 'PUT');
  };

  request.patch = function(uri, options) {
    return _create_method(uri, options, 'PATCH');
  };

  request.head = function(uri, options) {
    var deferred, req, _request;
    if (options == null) {
      options = {};
    }
    deferred = Q.defer();
    if (typeof (options != null ? options._requester : void 0) === 'function') {
      _request = options._requester;
    } else {
      _request = r;
    }
    req = _request.head(uri, options, function(err, res) {
      if (err) {
        return deferred.reject(err);
      } else {
        return deferred.resolve(res);
      }
    });
    return deferred.promise;
  };

  request.del = function(uri, options) {
    return _create_method(uri, options, 'DELETE');
  };

  request.initParams = r.initParams;

  request.jar = r.jar;

  request.cookie = r.cookie;

  request.defaults = function(options) {
    var de, def, key, requester, _i, _len, _ref;
    if (options == null) {
      options = {};
    }
    if (typeof options._requester === 'function') {
      requester = options._requester;
    } else {
      requester = request;
    }
    def = function(method) {
      return function(uri, opt) {
        var key, params, value;
        params = r.initParams(uri, opt, null);
        for (key in options) {
          value = options[key];
          if (params.options[key] === void 0) {
            params.options[key] = value;
          }
        }
        params.options._requester = requester;
        return method(params.uri, params.options);
      };
    };
    de = def(requester);
    _ref = ['get', 'post', 'put', 'patch', 'head', 'del', 'cookie'];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      key = _ref[_i];
      de[key] = def(requester[key]);
    }
    de.jar = requester.jar;
    de.defaults = function(opt) {
      var params, value;
      params = r.initParams(null, opt, null);
      for (key in options) {
        value = options[key];
        if (params.options[key] === void 0) {
          params.options[key] = value;
        }
      }
      params.options._requester = requester;
      return requester.defaults(params.options);
    };
    return de;
  };

  module.exports = request;

}).call(this);
