// Generated by CoffeeScript 1.6.3
(function() {
  var Q, r, request;

  Q = require('q');

  r = require('request');

  request = function(uri) {
    var deferred, req;
    deferred = Q.defer();
    req = r(uri, function(err, res) {
      if (err) {
        return deferred.reject(err);
      } else {
        return deferred.resolve(res);
      }
    });
    return deferred.promise;
  };

  module.exports = request;

}).call(this);
